# Generated by Django 5.2.14 on 2026-05-14 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contabilidad',
            fields=[
                ('idcontabilidad', models.IntegerField(db_column='idContabilidad', primary_key=True, serialize=False)),
                ('nombre_empresa', models.CharField(db_column='Nombre_Empresa', max_length=45)),
                ('reporte', models.CharField(db_column='Reporte', max_length=1)),
                ('total', models.DecimalField(db_column='Total', decimal_places=2, max_digits=10)),
                ('fecha_edicion', models.DateTimeField(db_column='Fecha_Edicion')),
            ],
            options={
                'db_table': 'contabilidad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VentaFactura',
            fields=[
                ('idventa_factura', models.IntegerField(db_column='idVenta_Factura', primary_key=True, serialize=False)),
                ('fecha_pedido', models.DateTimeField(db_column='Fecha_Pedido')),
                ('mÚtodo_pago', models.CharField(db_column='MÚtodo_pago', max_length=45)),
                ('impuesto_iva', models.DecimalField(db_column='Impuesto_Iva', decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(db_column='Total', decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'venta_factura',
                'managed': False,
            },
        ),
    ]
