# Generated by Django 5.2.14 on 2026-05-19 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProducto',
            fields=[
                ('category_id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=255)),
            ],
            options={
                'db_table': 'categoria_producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('idinventario', models.AutoField(db_column='idInventario', primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(db_column='Cantidad')),
                ('precio_compra_unitario', models.DecimalField(db_column='Precio_Compra_Unitario', decimal_places=2, max_digits=10)),
                ('fecha_entrada', models.DateTimeField(db_column='Fecha_Entrada')),
                ('observaciones', models.CharField(db_column='Observaciones', max_length=255)),
            ],
            options={
                'db_table': 'inventario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idproducto', models.IntegerField(db_column='idProducto', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=45)),
                ('stock', models.IntegerField(db_column='Stock')),
                ('precio_venta', models.DecimalField(db_column='Precio_Venta', decimal_places=2, max_digits=10)),
                ('descripcion', models.CharField(db_column='Descripcion', max_length=200)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='productos/')),
            ],
            options={
                'db_table': 'producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CategoriaHasProductos',
            fields=[
                ('categoria_idcategoria', models.ForeignKey(db_column='Categoria_idCategoria', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Producto.categoriaproducto')),
            ],
            options={
                'db_table': 'categoria_has_productos',
                'managed': False,
            },
        ),
    ]
