-- MySQL Script generated by MySQL Workbench
-- Mon May 11 09:03:48 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Categoria_has_Productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Categoria_has_Productos` (
  `Categoria_idCategoria` INT NOT NULL,
  `Productos_idProductos` INT NOT NULL,
  PRIMARY KEY (`Categoria_idCategoria`, `Productos_idProductos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuarios` (
  `Idusuario` VARCHAR(16) NOT NULL,
  `Nombre` VARCHAR(255) NOT NULL,
  `Email` VARCHAR(200) NOT NULL,
  `Contrasena` VARCHAR(255) NOT NULL,
  `Telefono` INT NOT NULL,
  `Direccion` VARCHAR(45) NOT NULL,
  `Estado` ENUM("A", "I") NOT NULL COMMENT 'A= Activo\nI = Inactivo',
  PRIMARY KEY (`Idusuario`));


-- -----------------------------------------------------
-- Table `mydb`.`Categoria_Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Categoria_Producto` (
  `category_id` INT NOT NULL,
  `Nombre` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`category_id`));


-- -----------------------------------------------------
-- Table `mydb`.`Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Producto` (
  `idProducto` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Stock` INT NOT NULL,
  `Precio_Venta` DECIMAL(10,2) NOT NULL,
  `Descripcion` VARCHAR(200) NOT NULL,
  `Usuarios_Idusuario` VARCHAR(16) NOT NULL,
  `category_category_id` INT NOT NULL,
  PRIMARY KEY (`idProducto`, `Usuarios_Idusuario`, `category_category_id`),
  INDEX `fk_Producto_Usuarios1_idx` (`Usuarios_Idusuario` ASC) VISIBLE,
  INDEX `fk_Producto_category1_idx` (`category_category_id` ASC) VISIBLE,
  CONSTRAINT `fk_Producto_Usuarios1`
    FOREIGN KEY (`Usuarios_Idusuario`)
    REFERENCES `mydb`.`Usuarios` (`Idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Producto_category1`
    FOREIGN KEY (`category_category_id`)
    REFERENCES `mydb`.`Categoria_Producto` (`category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Categoria_Servicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Categoria_Servicio` (
  `category_id` INT NOT NULL,
  `Nombre` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`category_id`));


-- -----------------------------------------------------
-- Table `mydb`.`Servicios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Servicios` (
  `idServicios` INT NOT NULL,
  `Nombre_Servicio` VARCHAR(45) NOT NULL,
  `Disponibilidad_servicio` ENUM("D", "ND") NOT NULL COMMENT 'D= Disponibilidad\nND = No Disponible',
  `Descripcion_Servicio` VARCHAR(200) NOT NULL,
  `Precio` DECIMAL(10,2) NOT NULL,
  `Fecha_inicial` DATETIME NOT NULL,
  `Fecha_final` DATETIME NOT NULL,
  `Usuarios_Idusuario` VARCHAR(16) NOT NULL,
  `Categoria_Servicio_category_id` INT NOT NULL,
  PRIMARY KEY (`idServicios`, `Usuarios_Idusuario`, `Categoria_Servicio_category_id`),
  INDEX `fk_Servicios_Usuarios1_idx` (`Usuarios_Idusuario` ASC) VISIBLE,
  INDEX `fk_Servicios_Categoria_Servicio1_idx` (`Categoria_Servicio_category_id` ASC) VISIBLE,
  CONSTRAINT `fk_Servicios_Usuarios1`
    FOREIGN KEY (`Usuarios_Idusuario`)
    REFERENCES `mydb`.`Usuarios` (`Idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Servicios_Categoria_Servicio1`
    FOREIGN KEY (`Categoria_Servicio_category_id`)
    REFERENCES `mydb`.`Categoria_Servicio` (`category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Carrito_Compras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Carrito_Compras` (
  `idCarrito_Compras` INT NOT NULL,
  `Subtotal` DECIMAL(10,2) NOT NULL,
  `Total` DECIMAL(10,2) NOT NULL,
  `Fecha_Creación` DATETIME NOT NULL,
  `Estado` ENUM("A", "I") NOT NULL COMMENT 'A= Activo\nI = Inactivo',
  `Usuarios_Idusuario` VARCHAR(16) NOT NULL,
  PRIMARY KEY (`idCarrito_Compras`, `Usuarios_Idusuario`),
  INDEX `fk_Carrito_Compras_Usuarios1_idx` (`Usuarios_Idusuario` ASC) VISIBLE,
  CONSTRAINT `fk_Carrito_Compras_Usuarios1`
    FOREIGN KEY (`Usuarios_Idusuario`)
    REFERENCES `mydb`.`Usuarios` (`Idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Contabilidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Contabilidad` (
  `idContabilidad` INT NOT NULL,
  `Nombre_Empresa` VARCHAR(45) NOT NULL,
  `Reporte` ENUM("I", "E") NOT NULL COMMENT 'I= Ingresos\nE= Egresos',
  `Total` DECIMAL(10,2) NOT NULL,
  `Fecha_Edicion` DATETIME NOT NULL,
  PRIMARY KEY (`idContabilidad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Venta_Factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Venta_Factura` (
  `idVenta_Factura` INT NOT NULL,
  `Fecha_Pedido` DATETIME NOT NULL,
  `Méusuariosusuariostodo_pago` VARCHAR(45) NOT NULL,
  `Impuesto_Iva` DECIMAL(10,2) NOT NULL,
  `Total` DECIMAL(10,2) NOT NULL,
  `Contabilidad_idContabilidad` INT NOT NULL,
  PRIMARY KEY (`idVenta_Factura`, `Contabilidad_idContabilidad`),
  INDEX `fk_Venta_Factura_Contabilidad1_idx` (`Contabilidad_idContabilidad` ASC) VISIBLE,
  CONSTRAINT `fk_Venta_Factura_Contabilidad1`
    FOREIGN KEY (`Contabilidad_idContabilidad`)
    REFERENCES `mydb`.`Contabilidad` (`idContabilidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Detalle_Venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Detalle_Venta` (
  `idDetalle_Venta` INT NOT NULL,
  `Cantidad` INT NOT NULL,
  `Precio_Unitario` DECIMAL(10,2) NOT NULL,
  `Fecha_pago` DATETIME NOT NULL,
  `Venta_Factura_idVenta_Factura` INT NOT NULL,
  `Producto_idProducto` INT NOT NULL,
  `Producto_Usuarios_Idusuario` VARCHAR(16) NOT NULL,
  `Producto_category_category_id` INT NOT NULL,
  `Servicios_idServicios` INT NOT NULL,
  `Servicios_Usuarios_Idusuario` VARCHAR(16) NOT NULL,
  `Servicios_Categoria_Servicio_category_id` INT NOT NULL,
  PRIMARY KEY (`idDetalle_Venta`, `Venta_Factura_idVenta_Factura`, `Producto_idProducto`, `Producto_Usuarios_Idusuario`, `Producto_category_category_id`, `Servicios_idServicios`, `Servicios_Usuarios_Idusuario`, `Servicios_Categoria_Servicio_category_id`),
  INDEX `fk_Detalle_Venta_Venta_Factura1_idx` (`Venta_Factura_idVenta_Factura` ASC) VISIBLE,
  INDEX `fk_Detalle_Venta_Producto1_idx` (`Producto_idProducto` ASC, `Producto_Usuarios_Idusuario` ASC, `Producto_category_category_id` ASC) VISIBLE,
  INDEX `fk_Detalle_Venta_Servicios1_idx` (`Servicios_idServicios` ASC, `Servicios_Usuarios_Idusuario` ASC, `Servicios_Categoria_Servicio_category_id` ASC) VISIBLE,
  CONSTRAINT `fk_Detalle_Venta_Venta_Factura1`
    FOREIGN KEY (`Venta_Factura_idVenta_Factura`)
    REFERENCES `mydb`.`Venta_Factura` (`idVenta_Factura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Detalle_Venta_Producto1`
    FOREIGN KEY (`Producto_idProducto` , `Producto_Usuarios_Idusuario` , `Producto_category_category_id`)
    REFERENCES `mydb`.`Producto` (`idProducto` , `Usuarios_Idusuario` , `category_category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Detalle_Venta_Servicios1`
    FOREIGN KEY (`Servicios_idServicios` , `Servicios_Usuarios_Idusuario` , `Servicios_Categoria_Servicio_category_id`)
    REFERENCES `mydb`.`Servicios` (`idServicios` , `Usuarios_Idusuario` , `Categoria_Servicio_category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Inventario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Inventario` (
  `idInventario` INT NOT NULL AUTO_INCREMENT,
  `Cantidad` INT NOT NULL,
  `Precio_Compra_Unitario` DECIMAL(10,2) NOT NULL,
  `Fecha_Entrada` DATETIME NOT NULL,
  `Observaciones` VARCHAR(255) NOT NULL,
  `Producto_idProducto` INT NOT NULL,
  `Producto_Usuarios_Idusuario` VARCHAR(16) NOT NULL,
  `Producto_category_category_id` INT NOT NULL,
  PRIMARY KEY (`idInventario`, `Producto_idProducto`, `Producto_Usuarios_Idusuario`, `Producto_category_category_id`),
  INDEX `fk_Inventario_Producto1_idx` (`Producto_idProducto` ASC, `Producto_Usuarios_Idusuario` ASC, `Producto_category_category_id` ASC) VISIBLE,
  CONSTRAINT `fk_Inventario_Producto1`
    FOREIGN KEY (`Producto_idProducto` , `Producto_Usuarios_Idusuario` , `Producto_category_category_id`)
    REFERENCES `mydb`.`Producto` (`idProducto` , `Usuarios_Idusuario` , `category_category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Rol` (
  `idRol` INT NOT NULL,
  `Nombre_Rol` VARCHAR(120) NOT NULL,
  PRIMARY KEY (`idRol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Detalle_carrito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Detalle_carrito` (
  `idDetalle_carrito` INT NOT NULL,
  `Cantidad` INT NOT NULL,
  `Precio_Unitario` DECIMAL(10,2) NOT NULL,
  `Carrito_Compras_idCarrito_Compras` INT NOT NULL,
  `Carrito_Compras_Usuarios_Idusuario` VARCHAR(16) NOT NULL,
  `Producto_idProducto` INT NOT NULL,
  `Producto_Usuarios_Idusuario` VARCHAR(16) NOT NULL,
  `Producto_category_category_id` INT NOT NULL,
  `Servicios_idServicios` INT NOT NULL,
  `Servicios_Usuarios_Idusuario` VARCHAR(16) NOT NULL,
  `Servicios_Categoria_Servicio_category_id` INT NOT NULL,
  PRIMARY KEY (`idDetalle_carrito`, `Carrito_Compras_idCarrito_Compras`, `Carrito_Compras_Usuarios_Idusuario`, `Producto_idProducto`, `Producto_Usuarios_Idusuario`, `Producto_category_category_id`, `Servicios_idServicios`, `Servicios_Usuarios_Idusuario`, `Servicios_Categoria_Servicio_category_id`),
  INDEX `fk_Detalle_carrito_Carrito_Compras1_idx` (`Carrito_Compras_idCarrito_Compras` ASC, `Carrito_Compras_Usuarios_Idusuario` ASC) VISIBLE,
  INDEX `fk_Detalle_carrito_Producto1_idx` (`Producto_idProducto` ASC, `Producto_Usuarios_Idusuario` ASC, `Producto_category_category_id` ASC) VISIBLE,
  INDEX `fk_Detalle_carrito_Servicios1_idx` (`Servicios_idServicios` ASC, `Servicios_Usuarios_Idusuario` ASC, `Servicios_Categoria_Servicio_category_id` ASC) VISIBLE,
  CONSTRAINT `fk_Detalle_carrito_Carrito_Compras1`
    FOREIGN KEY (`Carrito_Compras_idCarrito_Compras` , `Carrito_Compras_Usuarios_Idusuario`)
    REFERENCES `mydb`.`Carrito_Compras` (`idCarrito_Compras` , `Usuarios_Idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Detalle_carrito_Producto1`
    FOREIGN KEY (`Producto_idProducto` , `Producto_Usuarios_Idusuario` , `Producto_category_category_id`)
    REFERENCES `mydb`.`Producto` (`idProducto` , `Usuarios_Idusuario` , `category_category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Detalle_carrito_Servicios1`
    FOREIGN KEY (`Servicios_idServicios` , `Servicios_Usuarios_Idusuario` , `Servicios_Categoria_Servicio_category_id`)
    REFERENCES `mydb`.`Servicios` (`idServicios` , `Usuarios_Idusuario` , `Categoria_Servicio_category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuarios_has_Rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuarios_has_Rol` (
  `Usuarios_Idusuario` VARCHAR(16) NOT NULL,
  `Rol_idRol` INT NOT NULL,
  PRIMARY KEY (`Usuarios_Idusuario`, `Rol_idRol`),
  INDEX `fk_Usuarios_has_Rol_Rol1_idx` (`Rol_idRol` ASC) VISIBLE,
  INDEX `fk_Usuarios_has_Rol_Usuarios_idx` (`Usuarios_Idusuario` ASC) VISIBLE,
  CONSTRAINT `fk_Usuarios_has_Rol_Usuarios`
    FOREIGN KEY (`Usuarios_Idusuario`)
    REFERENCES `mydb`.`Usuarios` (`Idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuarios_has_Rol_Rol1`
    FOREIGN KEY (`Rol_idRol`)
    REFERENCES `mydb`.`Rol` (`idRol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

 

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
