# Generated by Django 5.2.14 on 2026-05-14 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarritoCompras',
            fields=[
                ('idcarrito_compras', models.IntegerField(db_column='idCarrito_Compras', primary_key=True, serialize=False)),
                ('subtotal', models.DecimalField(db_column='Subtotal', decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(db_column='Total', decimal_places=2, max_digits=10)),
                ('fecha_creacion', models.DateTimeField(db_column='Fecha_Creación')),
                ('estado', models.CharField(db_column='Estado', max_length=1)),
            ],
            options={
                'db_table': 'carrito_compras',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CategoriaHasProductos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'categoria_has_productos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CategoriaProducto',
            fields=[
                ('category_id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=255)),
            ],
            options={
                'db_table': 'categoria_producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CategoriaServicio',
            fields=[
                ('category_id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=255)),
            ],
            options={
                'db_table': 'categoria_servicio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleCarrito',
            fields=[
                ('iddetalle_carrito', models.IntegerField(db_column='idDetalle_carrito', primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(db_column='Cantidad')),
                ('precio_unitario', models.DecimalField(db_column='Precio_Unitario', decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'detalle_carrito',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('iddetalle_venta', models.IntegerField(db_column='idDetalle_Venta', primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(db_column='Cantidad')),
                ('precio_unitario', models.DecimalField(db_column='Precio_Unitario', decimal_places=2, max_digits=10)),
                ('fecha_pago', models.DateTimeField(db_column='Fecha_pago')),
            ],
            options={
                'db_table': 'detalle_venta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('idinventario', models.AutoField(db_column='idInventario', primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(db_column='Cantidad')),
                ('precio_compra_unitario', models.DecimalField(db_column='Precio_Compra_Unitario', decimal_places=2, max_digits=10)),
                ('fecha_entrada', models.DateTimeField(db_column='Fecha_Entrada')),
                ('observaciones', models.CharField(db_column='Observaciones', max_length=255)),
            ],
            options={
                'db_table': 'inventario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idproducto', models.IntegerField(db_column='idProducto', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=45)),
                ('stock', models.IntegerField(db_column='Stock')),
                ('precio_venta', models.DecimalField(db_column='Precio_Venta', decimal_places=2, max_digits=10)),
                ('descripcion', models.CharField(db_column='Descripcion', max_length=200)),
            ],
            options={
                'db_table': 'producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('idrol', models.IntegerField(db_column='idRol', primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(db_column='Nombre_Rol', max_length=120)),
            ],
            options={
                'db_table': 'rol',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('idservicios', models.IntegerField(db_column='idServicios', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=45)),
                ('precio', models.DecimalField(db_column='Precio', decimal_places=2, max_digits=10)),
                ('descripcion', models.CharField(db_column='Descripcion', max_length=200)),
            ],
            options={
                'db_table': 'servicios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('idusuario', models.IntegerField(db_column='idUsuario', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=45)),
                ('apellido', models.CharField(db_column='Apellido', max_length=45)),
                ('telefono', models.CharField(db_column='Telefono', max_length=15)),
                ('email', models.CharField(db_column='Email', max_length=45)),
                ('contraseña', models.CharField(db_column='Contraseña', max_length=45)),
                ('estado', models.CharField(db_column='Estado', max_length=1)),
            ],
            options={
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsuariosHasRol',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'usuarios_has_rol',
                'managed': False,
            },
        ),
    ]
